#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Sequence

from knowledge_ingest import (
    build_source_note,
    extract_item_id,
    fetch_source_feed,
    latest_published,
    load_config,
    merge_seen_ids,
    note_filename,
    write_json,
)
from phase11_bootstrap_writer_marketing import (
    replace_bundle_block,
    replace_canonical_notes_block,
    write_note,
    write_note_body,
)
from phase12_external_writer_marketing import (
    build_frontmatter,
    confidence_label,
    confidence_score,
    freshness_label,
    freshness_score,
    latest_source_signal,
)


HOME = Path.home()
BASE = HOME / "squad_memory"
DEFAULT_CONFIG = BASE / "knowledge_sources_support.json"
DEFAULT_SKILLS_ROOT = HOME / ".codex" / "skills"
DEFAULT_PHASE23_DIR = BASE / "ingest" / "phase23"
DEFAULT_DB_PATH = BASE / "squad_memory.db"
TODAY = date(2026, 3, 20)
PHASE23_BEGIN = "<!-- phase23:begin -->"
PHASE23_END = "<!-- phase23:end -->"

SUPPORT_CONFIG: Dict[str, Any] = {
    "label": "Support / Anemone",
    "router": "MEMORY.md",
    "operating_canon": "memory/anemone-operating-canon-2026.md",
    "external_canon_filename": "support-external-source-canon-2026.md",
    "summary_note": "live-external-source-monitor.md",
    "topic": "support_external_sources",
    "intent": "monitoring, research, support_examples, help_center_patterns, escalation_patterns",
    "role": "support-anemone, pinchy, operations, writer, support",
    "use_for": "fresh_examples, source_selection, support_monitoring, documentation_patterns",
    "avoid_for": "final_customer_promises_without_internal_confirmation, ad_hoc_product_policy_changes",
    "canonical_group": "Support external source canon",
    "bundle_roles": ["Anemone", "Pinchy", "Urchin", "Chitin"],
    "consensus": [
        "Fresh support sources are best used for support-system patterns, documentation ideas, and escalation hygiene, not for replacing the core Anemone operating canon.",
        "The strongest support sources reinforce quick acknowledgement, clear ownership, self-serve documentation, and high-quality internal handoffs.",
    ],
    "tension": [
        "The main tradeoff is empathy versus system discipline: customer-friendly language matters, but durable support improvement comes from repeatable triage, docs, and escalation loops.",
    ],
    "action": "Start with the Anemone operating canon for the workflow, then use this external canon for fresh support examples, documentation patterns, and help-desk operating research.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase 23 external source ingestion and fusion for support")
    parser.add_argument("--config", default=str(DEFAULT_CONFIG))
    parser.add_argument("--skills-root", default=str(DEFAULT_SKILLS_ROOT))
    parser.add_argument("--phase23-dir", default=str(DEFAULT_PHASE23_DIR))
    parser.add_argument("--db-path", default=str(DEFAULT_DB_PATH))
    parser.add_argument("--top", type=int, default=5)
    parser.add_argument("--build-db", action="store_true")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text())


def select_sources(config: Dict[str, Any]) -> List[Dict[str, Any]]:
    selected: List[Dict[str, Any]] = []
    for source in config.get("sources", []):
        if source.get("enabled", True) is not False:
            selected.append(source)
    return selected


def build_domain_summary_note(results: Sequence[Dict[str, Any]], snapshot_hint: Path) -> str:
    ok_results = [result for result in results if result["status"] == "ok"]
    error_results = [result for result in results if result["status"] != "ok"]
    lines = [
        "---",
        "source: local phase23 support external source ingest",
        "title: Support External Source Monitor",
        f"scraped: {datetime.now(timezone.utc).date().isoformat()}",
        "tags: phase23_external_sources, support, monitoring, freshness",
        f"topic: {SUPPORT_CONFIG['topic']}",
        f"intent: {SUPPORT_CONFIG['intent']}",
        f"role: {SUPPORT_CONFIG['role']}",
        "confidence: medium",
        "canonical: true",
        "canonical_group: Support live external monitor",
        "use_for: freshness, source_selection, support_research",
        "avoid_for: final_strategy_without_core_canon",
        "---",
        "",
        "# Support External Source Monitor",
        "",
        "This note is generated by Phase 23. Use it to spot fresh support-system, help-center, and customer-ops source activity before opening the support external canon or source-specific canons.",
        "",
        "## Health Summary",
        f"- Active sources: {len(results)}",
        f"- Healthy sources: {len(ok_results)}",
        f"- Failed sources: {len(error_results)}",
        "",
        "## Source Status",
    ]
    for result in results:
        if result["status"] == "ok":
            lines.append(
                f"- {result['name']}: ok | items={result['item_count']} | new={result['new_item_count']} | latest={result.get('latest_published') or 'unknown'} | note=`{result['note_filename']}`"
            )
        else:
            lines.append(f"- {result['name']}: error | {result.get('error', 'unknown error')}")
    lines.extend(["", "## Snapshot Notes"])
    for result in results:
        lines.append(f"- `{result['note_filename']}`")
    lines.extend(["", "## Storage", f"- Raw snapshots: `{snapshot_hint}`"])
    return "\n".join(lines).rstrip() + "\n"


def build_source_canon_note(source_cfg: Dict[str, Any], result: Dict[str, Any], top_n: int) -> str:
    items = result.get("items", [])[:top_n]
    lines = [
        "---",
        f"source: {source_cfg.get('homepage', '')}",
        f"title: Live Source Canon - {source_cfg['name']}",
        f"scraped: {datetime.now(timezone.utc).date().isoformat()}",
        f"tags: live_source_canon, phase23_external_sources, support, {source_cfg['slug']}",
        f"topic: {source_cfg.get('topic', SUPPORT_CONFIG['topic'])}",
        f"intent: {', '.join(source_cfg.get('intent', []))}",
        f"role: {', '.join(source_cfg.get('roles', []))}",
        f"confidence: {source_cfg.get('confidence', 'medium')}",
        "canonical: true",
        "canonical_group: Support live source canon",
        "use_for: fresh examples, support research, documentation monitoring",
        "avoid_for: final_strategy_without_core_canon",
        "---",
        "",
        f"# Live Source Canon - {source_cfg['name']}",
        "",
        f"Raw source note: [{result['note_filename']}](./{result['note_filename']})",
        f"Homepage: {source_cfg.get('homepage', '')}",
        f"Source kind: {source_cfg.get('kind', 'publication')}",
        f"Latest published date: {result.get('latest_published') or 'unknown'}",
        f"New items since last run: {result.get('new_item_count', 0)}",
        "",
        "## Best Use",
        source_cfg.get("strength", "Use this source for fresh support-system and documentation patterns."),
        "",
        "## Latest Signals",
    ]
    if result["status"] != "ok" or not items:
        lines.append(f"- Feed status: {result['status']} | {result.get('error', 'no items parsed')}")
    else:
        for item in items:
            lines.append(f"- {item['published']} | [{item['title']}]({item['link']})")
    lines.extend(
        [
            "",
            "## Agent Checklist",
            "- Use this source for freshness first, then map the signal back into the Anemone operating canon.",
            "- Pull one reusable support-system pattern, documentation move, or escalation idea before using the source in final advice.",
            "- Promote a durable note only if the update changes how the squad should triage, document, or hand off customer issues.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def build_external_canon(results: Sequence[Dict[str, Any]]) -> str:
    ok_results = [result for result in results if result["status"] == "ok"]
    error_results = [result for result in results if result["status"] != "ok"]
    source_rows = ok_results or list(results)
    lines = [
        build_frontmatter(
            {
                "title": "Support External Source Canon 2026",
                "topic": SUPPORT_CONFIG["topic"],
                "intent": SUPPORT_CONFIG["intent"],
                "role": SUPPORT_CONFIG["role"],
                "use_for": SUPPORT_CONFIG["use_for"],
                "avoid_for": SUPPORT_CONFIG["avoid_for"],
                "confidence": "high",
                "canonical": "true",
                "canonical_group": SUPPORT_CONFIG["canonical_group"],
                "source": "phase23_external_sources",
                "scraped": datetime.now(timezone.utc).date().isoformat(),
                "tags": "phase23, support, external sources, canon, squad",
            }
        ).rstrip(),
        "# Support External Source Canon 2026",
        "",
        "## Core Concept",
        SUPPORT_CONFIG["consensus"][0] + " " + SUPPORT_CONFIG["consensus"][1],
        "",
        "## Best Sources",
    ]
    for result in source_rows:
        lines.append(f"- **{result['name']}**: {result['strength']}. Latest signal: {latest_source_signal(result)}.")
    if error_results:
        lines.extend(["", "## Unavailable Sources"])
        for result in error_results:
            lines.append(f"- **{result['name']}**: {result.get('error', 'unknown error')}.")
    lines.extend(
        [
            "",
            "## Workflow Map",
            "1. Start with `memory/anemone-operating-canon-2026.md` for the default support operating system.",
            "2. Open this external canon when the task needs fresh support examples, help-center patterns, or source-aware support research.",
        ]
    )
    for idx, result in enumerate(source_rows, start=3):
        lines.append(f"{idx}. Open `memory/live-source-canon-{result['slug']}.md` when the task needs source-specific context from {result['name']}.")
    lines.extend(
        [
            "",
            "## Team Use",
            "- **Anemone**: Use this canon for fresh support examples and documentation patterns without abandoning the core support system.",
            "- **Pinchy**: Use this canon when the ask explicitly needs support benchmarks, help-center patterns, or external support research.",
            "- **Urchin**: Use this canon when support queue operations need fresh patterns for documentation or escalation hygiene.",
            "- **Plankton**: Use this canon when repeated support questions should turn into clearer docs or help-center content.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def build_phase23_block(evidence: Dict[str, Any]) -> str:
    lines = [
        "## Phase 23 External Source Fusion",
        "",
        f"Evidence confidence: {evidence['confidence_label']}",
        f"Freshness status: {evidence['freshness_label']}",
        f"Distinct sources: {', '.join(evidence['distinct_sources']) if evidence['distinct_sources'] else 'none'}",
        "",
        "### Consensus",
    ]
    for row in evidence["consensus"]:
        lines.append(f"- {row}")
    lines.extend(["", "### Tension / Caveat"])
    for row in evidence["tension"]:
        lines.append(f"- {row}")
    lines.extend(["", "### Fresh Source Signals"])
    for item in evidence["source_signals"]:
        lines.append(f"- `{Path(item['path']).name}`: {item['summary']}")
    lines.extend(["", "### Squad Action", f"- {evidence['squad_action']}"])
    return "\n".join(lines)


def replace_phase23_block(body: str, block: str) -> str:
    managed = f"{PHASE23_BEGIN}\n{block.rstrip()}\n{PHASE23_END}"
    import re

    pattern = re.compile(r"\n?<!-- phase23:begin -->.*?<!-- phase23:end -->\n?", re.DOTALL)
    if pattern.search(body):
        return pattern.sub("\n\n" + managed + "\n", body).rstrip() + "\n"
    return body.rstrip() + "\n\n" + managed + "\n"


def domain_evidence(results: Sequence[Dict[str, Any]], canon_rel_path: str) -> Dict[str, Any]:
    confidence = confidence_score(results)
    freshness = freshness_score(results)
    distinct_sources = [result["name"] for result in results if result["status"] == "ok"]
    source_signals = [
        {
            "source": result["name"],
            "path": f"support-anemone/memory/live-source-canon-{result['slug']}.md",
            "summary": latest_source_signal(result),
        }
        for result in results
    ]
    return {
        "topic": SUPPORT_CONFIG["topic"],
        "domain": "support-anemone",
        "primary_path": canon_rel_path,
        "evidence_paths": [canon_rel_path, *[item["path"] for item in source_signals]],
        "distinct_sources": distinct_sources,
        "source_count": len(distinct_sources),
        "evidence_count": len(source_signals) + 1,
        "freshness_score": freshness,
        "freshness_label": freshness_label(freshness),
        "confidence_score": confidence,
        "confidence_label": confidence_label(confidence),
        "consensus": SUPPORT_CONFIG["consensus"],
        "tension": SUPPORT_CONFIG["tension"],
        "squad_action": SUPPORT_CONFIG["action"],
        "source_signals": source_signals,
    }


def build_report(result: Dict[str, Any]) -> str:
    lines = [
        "---",
        "source: local phase23 support external sources",
        "title: Support External Sources Report",
        f"scraped: {datetime.now(timezone.utc).date().isoformat()}",
        "tags: phase23_external_sources, support, canon, monitoring",
        "topic: support_external_sources",
        "intent: maintenance, monitoring, canon_fusion",
        "role: pinchy, support-anemone, operations, writer",
        "confidence: high",
        "canonical: false",
        "canonical_group: Support external source report",
        "use_for: source_monitoring, phase23_reporting",
        "avoid_for: seo_strategy",
        "---",
        "",
        "# Support External Sources Report",
        "",
        f"- External canon: `{result['external_canon_path']}`",
        f"- Sources processed: {result['source_count']}",
        f"- Healthy sources: {result['ok_source_count']}",
        f"- Failed sources: {result['error_source_count']}",
        f"- Live snapshot notes: {result['live_note_count']}",
        f"- Source canons refreshed: {result['source_canon_count']}",
        f"- Router updated: {result['router_changed']}",
        f"- Bundles updated: {', '.join(result['bundle_changes']) if result['bundle_changes'] else 'none'}",
        f"- Operating canon updated: {result['operating_canon_changed']}",
        "",
    ]
    if result["failed_sources"]:
        lines.append("## Failed Sources")
        for row in result["failed_sources"]:
            lines.append(f"- {row['name']}: {row['error']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def run(skills_root: Path, config_path: Path, phase23_dir: Path, db_path: Path, top_n: int, build_db: bool) -> Dict[str, Any]:
    config = load_config(config_path)
    phase23_dir.mkdir(parents=True, exist_ok=True)
    sources = select_sources(config)

    memory_root = skills_root / "support-anemone" / "memory"
    memory_root.mkdir(parents=True, exist_ok=True)
    router_path = skills_root / "support-anemone" / SUPPORT_CONFIG["router"]
    operating_canon_path = skills_root / "support-anemone" / SUPPORT_CONFIG["operating_canon"]
    external_canon_path = memory_root / SUPPORT_CONFIG["external_canon_filename"]
    summary_path = memory_root / SUPPORT_CONFIG["summary_note"]

    snapshot_dir = phase23_dir / "raw" / "support"
    state_path = phase23_dir / "state" / "support.json"
    snapshot_dir.mkdir(parents=True, exist_ok=True)
    state = load_json(state_path, {"generated_at": "", "sources": {}})
    now = datetime.now(timezone.utc)

    results: List[Dict[str, Any]] = []
    for source_cfg in sources:
        fetch_result = fetch_source_feed(source_cfg, snapshot_dir, now)
        items = fetch_result["items"]
        fetched_from = fetch_result["fetched_from"]
        previous = state.get("sources", {}).get(source_cfg["slug"], {})
        previous_seen = previous.get("seen_ids", [])
        current_ids = [extract_item_id(item) for item in items]
        previous_seen_set = set(previous_seen)
        new_item_count = len([item_id for item_id in current_ids if item_id and item_id not in previous_seen_set])

        result: Dict[str, Any] = {
            "domain": "support",
            "slug": source_cfg["slug"],
            "name": source_cfg["name"],
            "strength": source_cfg.get("strength", ""),
            "status": "ok" if fetched_from else "error",
            "fetched_from": fetched_from,
            "channel_title": fetch_result["channel_title"],
            "item_count": len(items),
            "new_item_count": new_item_count,
            "latest_published": latest_published(items),
            "snapshot_path": fetch_result["snapshot_path"],
            "items": items,
            "error": fetch_result["error"] if not fetched_from else "",
            "attempted_urls": fetch_result.get("attempted_urls", []),
            "discovered_urls": fetch_result.get("discovered_urls", []),
            "note_filename": note_filename(source_cfg),
        }

        note_text = build_source_note(source_cfg, result, top_n)
        (memory_root / result["note_filename"]).write_text(note_text, encoding="utf-8")
        result["note_path"] = str(memory_root / result["note_filename"])

        canon_filename = f"live-source-canon-{source_cfg['slug']}.md"
        canon_text = build_source_canon_note(source_cfg, result, top_n)
        (memory_root / canon_filename).write_text(canon_text, encoding="utf-8")
        result["canon_filename"] = canon_filename
        result["canon_path"] = str(memory_root / canon_filename)
        results.append(result)

        state.setdefault("sources", {})[source_cfg["slug"]] = {
            "name": source_cfg["name"],
            "last_success_at": now.isoformat() if fetched_from else previous.get("last_success_at", ""),
            "last_status": result["status"],
            "latest_published": result["latest_published"],
            "last_item_count": len(items),
            "last_new_item_count": new_item_count,
            "last_snapshot_path": result["snapshot_path"],
            "last_note_path": result["note_path"],
            "last_canon_path": result["canon_path"],
            "seen_ids": merge_seen_ids(current_ids, previous_seen),
        }

    summary_path.write_text(build_domain_summary_note(results, snapshot_dir), encoding="utf-8")
    state["generated_at"] = now.isoformat()
    write_json(state_path, state)

    external_canon_changed = write_note(external_canon_path, build_external_canon(results))
    router_changed = replace_canonical_notes_block(router_path, SUPPORT_CONFIG["external_canon_filename"])
    bundle_changes: List[str] = []
    for role_name in SUPPORT_CONFIG["bundle_roles"]:
        if replace_bundle_block(router_path, role_name, SUPPORT_CONFIG["external_canon_filename"]):
            bundle_changes.append(role_name)

    external_canon_rel = f"support-anemone/memory/{SUPPORT_CONFIG['external_canon_filename']}"
    evidence = domain_evidence(results, external_canon_rel)
    ledger_path = phase23_dir / "support_external_evidence_ledger.json"
    write_json(
        ledger_path,
        {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "topics": {SUPPORT_CONFIG["topic"]: evidence},
            "primary_paths": {external_canon_rel: evidence},
        },
    )

    operating_canon_changed = write_note_body(
        operating_canon_path,
        lambda body, evidence=evidence: replace_phase23_block(body, build_phase23_block(evidence)),
    )

    result: Dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "phase23_dir": str(phase23_dir),
        "config_path": str(config_path),
        "external_canon_path": external_canon_rel,
        "source_count": len(results),
        "ok_source_count": len([item for item in results if item["status"] == "ok"]),
        "error_source_count": len([item for item in results if item["status"] != "ok"]),
        "live_note_count": len(results),
        "source_canon_count": len(results),
        "router_changed": router_changed,
        "bundle_changes": bundle_changes,
        "operating_canon_changed": operating_canon_changed or external_canon_changed,
        "ledger_path": str(ledger_path),
        "summary_path": str(summary_path),
        "failed_sources": [
            {"name": item["name"], "error": item.get("error", "unknown error")}
            for item in results
            if item["status"] != "ok"
        ],
    }

    report_path = phase23_dir / "support_external_sources_report.md"
    report_path.write_text(build_report(result), encoding="utf-8")
    result["report_path"] = str(report_path)

    if build_db:
        completed = subprocess.run(
            [
                sys.executable,
                str(BASE / "squad_memory.py"),
                "build",
                "--root",
                str(skills_root),
                "--db",
                str(db_path),
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            raise SystemExit(completed.returncode)
        result["build"] = {
            "returncode": completed.returncode,
            "stdout": completed.stdout.strip(),
            "stderr": completed.stderr.strip(),
            "db_path": str(db_path),
        }

    manifest_path = phase23_dir / f"phase23-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    write_json(manifest_path, result)
    write_json(phase23_dir / "latest.json", result)
    result["manifest_path"] = str(manifest_path)
    return result


def print_result(result: Dict[str, Any]) -> None:
    print(f"Report: {result['report_path']}")
    print(f"External canon: {result['external_canon_path']}")
    print(f"Sources: {result['source_count']}")
    if result.get("build"):
        print(f"Build DB: rc={result['build']['returncode']} db={result['build']['db_path']}")
        if result["build"]["stdout"]:
            print(result["build"]["stdout"])


def main() -> int:
    args = parse_args()
    result = run(
        skills_root=Path(args.skills_root),
        config_path=Path(args.config),
        phase23_dir=Path(args.phase23_dir),
        db_path=Path(args.db_path),
        top_n=args.top,
        build_db=args.build_db,
    )
    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=True))
    else:
        print_result(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
