#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple

from openclaw_hq_context import build_graph_hq_context
from refresh_local_seo_stack import refresh_local_seo_stack


HOME = Path.home()
DEFAULT_WORKSPACE = HOME / ".openclaw" / "workspace" / "squad" / "seo"
ROUTE_HISTORY_LIMIT = 36


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Refresh reusable OpenClaw SEO mission artifacts and route goals to the best local workflow"
    )
    parser.add_argument("--workspace", default=str(DEFAULT_WORKSPACE))
    parser.add_argument("--status-json", default=str(DEFAULT_WORKSPACE / "automation" / "data" / "latest-status.json"))
    parser.add_argument("--digest-json", default=str(DEFAULT_WORKSPACE / "automation" / "digest" / "latest.json"))
    parser.add_argument("--graph-hq-root", help="Optional shared graph/HQ import root")
    parser.add_argument("--goal", help="Optional plain-English SEO goal to route to the best workflow")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON")
    return parser.parse_args()


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def parse_iso_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(normalized)
    except ValueError:
        return None


def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_text(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()


def artifact_mode(path: Path) -> str:
    if not path.exists():
        return "missing"
    text = path.read_text(encoding="utf-8", errors="replace")
    if "Generated by deterministic fallback" in text or "Generated by HQ deterministic fallback" in text:
        return "fallback"
    if "Awaiting the first OpenClaw" in text:
        return "placeholder"
    return "live"


def artifact_snapshot(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {
            "path": str(path),
            "exists": False,
            "mode": "missing",
            "updated_at": None,
        }

    updated_at = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc).replace(microsecond=0).isoformat()
    return {
        "path": str(path),
        "exists": True,
        "mode": artifact_mode(path),
        "updated_at": updated_at,
    }


def mission_readme() -> str:
    return """# OpenClaw SEO Missions

This folder turns the local SEO stack into reusable missions instead of one-off prompts.

## Files
- `catalog.md`: the mission catalog mapped to local MCPs and knowledge layers.
- `prompts/*.md`: mission-specific prompts for isolated OpenClaw runs.
- `outbox/*.md`: deterministic fallback mission briefs that remain useful even when the model layer is unavailable.
- `prose/*.prose`: OpenProse-ready workflow programs generated from the same mission definitions.
- `execution/*.md`: workflow-specific execution queues with ordered tasks, status, and deliverables.
- `execution/current-queue.md`: the active execution queue for the selected mission.
- `../../memory/imports/codex/graph-hq/phase21/HQ_STATUS.md`: HQ pressure and queue/source health summary.
- `../../memory/imports/codex/graph-hq/phase31/GRAPH_STATUS.md`: graph topology and retrieval-health summary.
- `router/next-best-mission.json`: the deterministic automatic router output.
- `router/next-best-mission-deterministic.md`: the deterministic markdown summary of the best next mission.
- `router/next-best-mission.md`: the live agent-written mission output when the cron runner succeeds.
- `router/mission-scoreboard.md`: a ranked board of all missions with confidence, blockers, and score breakdowns.
- `router/history.json`: recent mission selections used for cooldown and anti-repeat behavior.
- `router/current-mission.md`: the prompt for the currently selected mission.

## Router
- Automatic mode ranks missions by strategic value, signal fit, readiness, execution fit, and cooldown penalties.
- Goal mode routes plain-English requests to the closest mission by keyword match plus current system state.
- Deterministic and live outputs are separated so the system can stay trustworthy even when a live run goes stale.
"""


def load_capabilities(workspace: Path) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    capabilities_dir = workspace / "automation" / "capabilities"
    stack_json = capabilities_dir / "local-stack.json"
    workflows_json = capabilities_dir / "workflows.json"
    if not stack_json.exists() or not workflows_json.exists():
        refresh_local_seo_stack(workspace)
    components = load_json(stack_json).get("components", [])
    workflows = load_json(workflows_json).get("workflows", [])
    return components, workflows


def component_labels(stack: List[str], components_by_id: Dict[str, Dict[str, Any]]) -> List[str]:
    labels: List[str] = []
    for component_id in stack:
        component = components_by_id.get(component_id, {})
        labels.append(component.get("label", component_id))
    return labels


def digest_keyword_matches(workflow: Dict[str, Any], digest: Dict[str, Any]) -> List[str]:
    digest_blob = normalize_text(
        " ".join(
            [
                digest.get("headline", ""),
                *[item.get("title", "") for item in digest.get("alerts", [])],
                *[item.get("details", "") for item in digest.get("alerts", [])],
                *[item.get("title", "") for item in digest.get("opportunities", [])],
                *[item.get("why_now", "") for item in digest.get("opportunities", [])],
                *[item.get("action", "") for item in digest.get("opportunities", [])],
            ]
        )
    )
    matches: List[str] = []
    for keyword in workflow.get("goal_keywords", []):
        normalized = normalize_text(keyword)
        if normalized and normalized in digest_blob:
            matches.append(keyword)
    return matches


def stack_readiness(workflow: Dict[str, Any], components_by_id: Dict[str, Dict[str, Any]]) -> Tuple[int, List[str], List[str]]:
    score = 0
    reasons: List[str] = []
    blockers: List[str] = []
    ready_count = 0
    partial_count = 0

    for component_id in workflow["stack"]:
        component = components_by_id.get(component_id, {})
        status = component.get("status", "missing")
        label = component.get("label", component_id)
        if status == "ready":
            score += 7
            ready_count += 1
        elif status == "partial":
            score += 2
            partial_count += 1
            blockers.append(f"{label} is only partially ready.")
        else:
            score -= 8
            blockers.append(f"{label} is missing.")

    if ready_count == len(workflow["stack"]):
        reasons.append("Every required local component is ready.")
    elif ready_count > 0:
        reasons.append(f"{ready_count} required component(s) are fully ready.")
    if partial_count > 0:
        reasons.append(f"{partial_count} component(s) are only partially ready and may need operator cleanup.")

    return score, reasons, blockers


def execution_fit_score(workflow: Dict[str, Any], goal: str | None) -> Tuple[int, str]:
    fit = workflow.get("automation_fit", "ambient")
    if goal:
        if fit == "ambient":
            return 8, "The mission still fits an explicit operator goal without needing extra routing context."
        if fit == "topic":
            return 10, "This workflow converts a named topic or request into a concrete plan cleanly."
        return 7, "This workflow becomes more practical once a specific goal or problem statement is present."

    if fit == "ambient":
        return 12, "This workflow can self-start from ambient system signals and local status alone."
    if fit == "topic":
        return 6, "This workflow is useful automatically, but it becomes stronger when a topic is named explicitly."
    return 2, "This workflow is strongest once a specific site, URL set, or query set is supplied."


def signal_fit_score(workflow: Dict[str, Any], payload: Dict[str, Any], digest: Dict[str, Any]) -> Tuple[int, List[str]]:
    workflow_id = workflow["id"]
    pending_total = int(payload.get("pending", {}).get("pending_total", 0))
    recent_fetch_ok = int(payload.get("activity", {}).get("recent_fetch_ok", 0))
    recent_fetch_error = int(payload.get("activity", {}).get("recent_fetch_error", 0))
    phase = payload.get("activity", {}).get("current_phase", "unknown")
    live_articles = payload.get("recent_knowledge", {}).get("live_articles", [])
    primary_source_notes = int(payload.get("coverage", {}).get("primary_source_notes", 0))
    inactive_jobs = [job for job in payload.get("active_jobs", []) if job.get("status") != "active"]
    alert_titles = [item.get("title", "") for item in digest.get("alerts", [])]
    opportunity_titles = [item.get("title", "") for item in digest.get("opportunities", [])]
    keyword_hits = digest_keyword_matches(workflow, digest)

    score = min(len(keyword_hits) * 4, 12)
    reasons: List[str] = []
    if keyword_hits:
        reasons.append(f"Digest language already matches this workflow: {', '.join(keyword_hits[:4])}.")

    if workflow_id == "freshness-radar":
        score += 18
        if live_articles:
            score += min(len(live_articles) * 4, 20)
            reasons.append(f"{len(live_articles)} fresh article notes are already available for same-day exploitation.")
        if recent_fetch_ok > 0:
            score += min(recent_fetch_ok, 10)
            reasons.append(f"The refresh layer still has positive movement (`recent_fetch_ok={recent_fetch_ok}`).")
        if phase in {"discovering", "harvesting", "expanding", "building"}:
            score += 8
            reasons.append(f"The current phase is `{phase}`, which favors freshness-first triage.")
    elif workflow_id == "gsc-opportunity-mining":
        score += 16
        if any("opportunity" in title.lower() for title in opportunity_titles):
            score += 8
            reasons.append("The digest already surfaced opportunity-shaped work worth turning into a GSC queue.")
        if recent_fetch_error == 0:
            score += 4
            reasons.append("No active refresh instability is distracting from traffic-lift work.")
    elif workflow_id == "cannibalization-cleanup":
        score += 10
        if pending_total < 500:
            score += 4
            reasons.append("The backlog is manageable enough to spend time on structural cleanup.")
        if any("pattern" in title.lower() for title in opportunity_titles):
            score += 4
            reasons.append("Repeated source patterns suggest overlap and consolidation checks may pay off.")
    elif workflow_id == "indexation-war-room":
        score += 14
        if recent_fetch_error > 0:
            score += min(recent_fetch_error * 5, 18)
            reasons.append(f"Recent error activity is non-zero (`recent_fetch_error={recent_fetch_error}`).")
        if inactive_jobs:
            score += min(len(inactive_jobs) * 6, 18)
            reasons.append(f"{len(inactive_jobs)} tracked job(s) are not active, which raises operational stability questions.")
        if any("missing" in title.lower() or "idle" in title.lower() for title in alert_titles):
            score += 8
            reasons.append("The alert layer contains stale-job or missing-signal warnings.")
    elif workflow_id == "content-gap-to-brief":
        score += 12
        if live_articles:
            score += min(len(live_articles) * 3, 12)
            reasons.append("Fresh source notes can be converted into tighter content briefs immediately.")
        if primary_source_notes > 0:
            score += 6
            reasons.append(f"The local canon already includes `{primary_source_notes}` primary-source notes for grounding.")
        if any("fresh source exploitation" in title.lower() for title in opportunity_titles):
            score += 6
            reasons.append("The digest already points to fresh-source exploitation work.")
    elif workflow_id == "technical-audit-sprint":
        score += 12
        if recent_fetch_error > 0:
            score += min(recent_fetch_error * 4, 12)
            reasons.append("Recent errors justify a technical pass before scaling further.")
        if inactive_jobs:
            score += 6
            reasons.append("Background job instability makes a technical pass more defensible.")
        if primary_source_notes < 10:
            score += 5
            reasons.append(f"The primary-source layer is still thin (`primary_source_notes={primary_source_notes}`).")

    if not reasons:
        reasons.append(f"{workflow['name']} remains a valid reusable workflow for this stack even without a strong live signal spike.")
    return score, reasons


def hq_signal_score(workflow: Dict[str, Any], hq_context: Dict[str, Any]) -> Tuple[int, List[str]]:
    if not hq_context.get("available"):
        return 0, []

    workflow_id = workflow["id"]
    phase21 = hq_context.get("phase21", {})
    phase31 = hq_context.get("phase31", {})

    alerts_total = max(int(phase21.get("alerts_total", 0)), int(phase31.get("alerts_total", 0)))
    seo_hold = int(phase21.get("seo_queue_hold", 0))
    stale_sources = int(phase21.get("seo_stale_sources", 0))
    seo_new_items = int(phase21.get("seo_new_items", 0))
    topics_total = int(phase31.get("topics_total", 0))
    memory_paths_total = int(phase31.get("memory_paths_total", 0))
    links_total = int(phase31.get("links_total", 0))
    meetings_total = int(phase31.get("meetings_total", 0))
    primary_skill_accuracy = float(phase31.get("primary_skill_accuracy", 0.0))
    pass_rate = float(phase31.get("pass_rate", 0.0))

    score = 0
    reasons: List[str] = []

    if workflow_id == "freshness-radar":
        if meetings_total > 0:
            score += 4
            reasons.append(f"HQ already shows `{meetings_total}` active meeting snapshot(s), so fresh evidence can feed live coordination.")
        if alerts_total <= 12:
            score += 3
            reasons.append("HQ pressure is elevated but still manageable, so freshness exploitation remains defensible.")
        if seo_new_items > 0:
            score += min(seo_new_items, 4)
            reasons.append(f"HQ source health still reports `{seo_new_items}` new SEO item(s) in the latest control-plane snapshot.")
    elif workflow_id == "gsc-opportunity-mining":
        if stale_sources <= 3:
            score += 4
            reasons.append("HQ source health is stable enough to spend time on traffic wins instead of pure recovery.")
        if primary_skill_accuracy >= 0.95:
            score += 4
            reasons.append(f"Graph retrieval quality is strong (`primary skill accuracy={primary_skill_accuracy:.2%}`), which supports tighter opportunity ranking.")
    elif workflow_id == "cannibalization-cleanup":
        if memory_paths_total >= 3000:
            score += 6
            reasons.append(f"The memory graph already spans `{memory_paths_total}` paths, which is enough topology for overlap cleanup.")
        if links_total >= 200:
            score += 4
            reasons.append(f"The graph has `{links_total}` links, so consolidation work can use richer relationship context.")
    elif workflow_id == "indexation-war-room":
        if stale_sources > 0:
            score += min(stale_sources * 3, 12)
            reasons.append(f"HQ is already flagging `{stale_sources}` stale SEO source(s), which makes recovery and indexing triage more urgent.")
        if alerts_total >= 8:
            score += 4
            reasons.append(f"The HQ alert load is high (`{alerts_total}` alerts), so war-room style triage is justified.")
    elif workflow_id == "content-gap-to-brief":
        if topics_total >= 40:
            score += 6
            reasons.append(f"The graph already maps `{topics_total}` topics, so gap analysis has enough coverage to produce a sharper brief.")
        if memory_paths_total >= 3000:
            score += 4
            reasons.append("The graph corpus is large enough to turn missing coverage into a more grounded content brief.")
        if meetings_total > 0:
            score += 3
            reasons.append("HQ has recent meeting context, which supports packaging findings into a brief for the next handoff.")
    elif workflow_id == "technical-audit-sprint":
        if alerts_total >= 8:
            score += 6
            reasons.append(f"HQ is carrying `{alerts_total}` alerts, which increases the case for a technical stabilization pass.")
        if primary_skill_accuracy and primary_skill_accuracy < 0.96:
            score += 4
            reasons.append(f"Graph evaluation slipped below the ideal threshold (`primary skill accuracy={primary_skill_accuracy:.2%}`), so deeper technical cleanup is defensible.")
        if pass_rate and pass_rate < 0.99:
            score += 3
            reasons.append(f"Task pass rate is only `{pass_rate:.2%}`, which supports an audit sprint before scaling execution.")
        if seo_hold >= 30:
            score += 3
            reasons.append(f"The SEO HQ queue has `{seo_hold}` held items, which may indicate structural friction worth auditing.")

    return score, reasons


def load_route_history(router_dir: Path) -> List[Dict[str, Any]]:
    history_path = router_dir / "history.json"
    raw = load_json(history_path).get("entries", [])
    return [entry for entry in raw if isinstance(entry, dict)]


def save_route_history(history_path: Path, entries: List[Dict[str, Any]]) -> None:
    history_path.write_text(
        json.dumps({"entries": entries[-ROUTE_HISTORY_LIMIT:]}, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )


def cooldown_penalty(workflow: Dict[str, Any], history: List[Dict[str, Any]], generated_at: str) -> Tuple[int, List[str], Dict[str, Any] | None]:
    now_dt = parse_iso_datetime(generated_at)
    if not now_dt:
        return 0, [], None

    workflow_id = workflow["id"]
    cooldown_hours = int(workflow.get("cooldown_hours", 8))
    previous = None
    for entry in reversed(history):
        if entry.get("selected_id") == workflow_id:
            previous = entry
            break
    if not previous:
        return 0, [], None

    previous_dt = parse_iso_datetime(previous.get("generated_at"))
    if not previous_dt:
        return 0, [], None

    age_hours = max((now_dt - previous_dt).total_seconds() / 3600.0, 0.0)
    if age_hours >= cooldown_hours:
        return 0, [], {"last_selected_at": previous.get("generated_at"), "age_hours": round(age_hours, 1)}

    remaining_ratio = max((cooldown_hours - age_hours) / cooldown_hours, 0.0)
    penalty = max(2, round(12 * remaining_ratio))
    reasons = [
        f"This mission was selected {age_hours:.1f}h ago, so a cooldown penalty was applied to avoid repeating the same play too often."
    ]
    history_context = {
        "last_selected_at": previous.get("generated_at"),
        "age_hours": round(age_hours, 1),
        "cooldown_hours": cooldown_hours,
    }
    return penalty, reasons, history_context


def confidence_for(score: int, blockers: List[str], readiness_score: int, signal_score: int) -> str:
    if blockers or readiness_score < 6:
        return "low"
    if score >= 60 and signal_score >= 20:
        return "high"
    if score >= 38:
        return "medium"
    return "low"


def evaluate_workflow(
    workflow: Dict[str, Any],
    payload: Dict[str, Any],
    digest: Dict[str, Any],
    hq_context: Dict[str, Any],
    components_by_id: Dict[str, Dict[str, Any]],
    history: List[Dict[str, Any]],
    goal: str | None = None,
) -> Dict[str, Any]:
    strategic_value = int(workflow.get("impact", 3)) * 5
    efficiency = max(2, (5 - int(workflow.get("effort", 3))) * 3)
    readiness_score, readiness_reasons, blockers = stack_readiness(workflow, components_by_id)
    signal_score, signal_reasons = signal_fit_score(workflow, payload, digest)
    hq_score, hq_reasons = hq_signal_score(workflow, hq_context)
    execution_fit, execution_reason = execution_fit_score(workflow, goal)
    cooldown_value, cooldown_reasons, history_context = cooldown_penalty(workflow, history, now_utc_iso())

    matched_keywords: List[str] = []
    goal_fit = 0
    goal_mismatch_penalty = 0
    goal_reasons: List[str] = []
    if goal:
        normalized_goal = normalize_text(goal)
        goal_tokens = set(normalized_goal.split())
        matched_keywords = [
            keyword
            for keyword in workflow.get("goal_keywords", [])
            if normalize_text(keyword) and normalize_text(keyword) in normalized_goal
        ]
        name_overlap = sorted(goal_tokens & set(normalize_text(workflow["name"]).split()))
        goal_fit += len(matched_keywords) * 30
        goal_fit += len(name_overlap) * 8
        if matched_keywords:
            goal_reasons.append(f"Goal matched mission keywords: {', '.join(matched_keywords[:4])}.")
        if name_overlap:
            goal_reasons.append(f"Goal overlaps with workflow naming: {', '.join(name_overlap)}.")
        if not matched_keywords and not name_overlap:
            goal_mismatch_penalty = 12
            goal_reasons.append("This workflow does not match the explicit goal language directly.")

    breakdown = {
        "strategic_value": strategic_value,
        "signal_fit": signal_score,
        "hq_fit": hq_score,
        "readiness": readiness_score,
        "execution_fit": execution_fit,
        "efficiency": efficiency,
        "goal_fit": goal_fit,
        "goal_mismatch_penalty": -goal_mismatch_penalty,
        "cooldown_penalty": -cooldown_value,
    }
    score = (
        strategic_value
        + signal_score
        + hq_score
        + readiness_score
        + execution_fit
        + efficiency
        + goal_fit
        - goal_mismatch_penalty
        - cooldown_value
    )
    confidence = confidence_for(score, blockers, readiness_score, signal_score + hq_score + goal_fit)

    reasons = goal_reasons + signal_reasons + hq_reasons + readiness_reasons
    reasons.append(execution_reason)
    reasons.extend(cooldown_reasons)

    if not reasons:
        reasons.append(f"{workflow['name']} remains viable for this stack.")

    return {
        "workflow": workflow,
        "score": score,
        "confidence": confidence,
        "reasons": reasons[:6],
        "blockers": blockers[:4],
        "score_breakdown": breakdown,
        "matched_keywords": matched_keywords,
        "history": history_context,
    }


def build_route_payload(
    selected_eval: Dict[str, Any],
    ranked_evals: List[Dict[str, Any]],
    components_by_id: Dict[str, Dict[str, Any]],
    source: str,
    hq_context: Dict[str, Any],
    goal: str | None = None,
) -> Dict[str, Any]:
    workflow = selected_eval["workflow"]
    alternatives: List[Dict[str, Any]] = []
    for evaluation in ranked_evals[1:4]:
        alt_workflow = evaluation["workflow"]
        alternatives.append(
            {
                "id": alt_workflow["id"],
                "name": alt_workflow["name"],
                "score": evaluation["score"],
                "confidence": evaluation["confidence"],
                "score_gap": selected_eval["score"] - evaluation["score"],
                "why": evaluation["reasons"][0],
            }
        )

    switch_conditions = [
        f"Watch `{item['name']}` if its signal improves enough to close the current {item['score_gap']}-point gap."
        for item in alternatives
        if item["score_gap"] <= 10
    ]
    if not switch_conditions:
        switch_conditions.append("Stay with the current mission until a new alert, opportunity, or explicit goal changes the scoreboard materially.")

    return {
        "generated_at": now_utc_iso(),
        "source": source,
        "goal": goal,
        "score": selected_eval["score"],
        "confidence": selected_eval["confidence"],
        "reasons": selected_eval["reasons"][:4],
        "blockers": selected_eval["blockers"],
        "score_breakdown": selected_eval["score_breakdown"],
        "hq": {
            "available": hq_context.get("available", False),
            "ready": hq_context.get("ready", False),
            "seo_queue_hold": hq_context.get("phase21", {}).get("seo_queue_hold", 0),
            "seo_stale_sources": hq_context.get("phase21", {}).get("seo_stale_sources", 0),
            "graph_topics_total": hq_context.get("phase31", {}).get("topics_total", 0),
            "graph_memory_paths_total": hq_context.get("phase31", {}).get("memory_paths_total", 0),
        },
        "history": selected_eval["history"],
        "selected": {
            "id": workflow["id"],
            "name": workflow["name"],
            "objective": workflow["objective"],
            "best_when": workflow["best_when"],
            "cadence": workflow["cadence"],
            "impact": workflow.get("impact"),
            "effort": workflow.get("effort"),
            "automation_fit": workflow.get("automation_fit"),
            "cooldown_hours": workflow.get("cooldown_hours"),
            "stack": workflow["stack"],
            "stack_labels": component_labels(workflow["stack"], components_by_id),
            "output": workflow["output"],
            "outbox_path": f"automation/missions/outbox/{workflow['id']}.md",
            "prompt_path": f"automation/missions/prompts/{workflow['id']}.md",
            "prose_path": f"automation/missions/prose/{workflow['id']}.prose",
            "queue_path": f"automation/missions/execution/{workflow['id']}.md",
            "current_queue_path": "automation/missions/execution/current-queue.md",
        },
        "alternatives": alternatives,
        "switch_conditions": switch_conditions,
    }


def rank_workflows(
    workflows: List[Dict[str, Any]],
    payload: Dict[str, Any],
    digest: Dict[str, Any],
    hq_context: Dict[str, Any],
    components_by_id: Dict[str, Dict[str, Any]],
    history: List[Dict[str, Any]],
    goal: str | None = None,
) -> List[Dict[str, Any]]:
    ranked = [
        evaluate_workflow(
            workflow=workflow,
            payload=payload,
            digest=digest,
            hq_context=hq_context,
            components_by_id=components_by_id,
            history=history,
            goal=goal,
        )
        for workflow in workflows
    ]
    ranked.sort(key=lambda item: (-item["score"], item["workflow"]["name"]))
    return ranked


def choose_automatic_route(
    workflows: List[Dict[str, Any]],
    payload: Dict[str, Any],
    digest: Dict[str, Any],
    hq_context: Dict[str, Any],
    components_by_id: Dict[str, Dict[str, Any]],
    history: List[Dict[str, Any]],
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    ranked = rank_workflows(workflows, payload, digest, hq_context, components_by_id, history)
    route = build_route_payload(ranked[0], ranked, components_by_id, source="automatic", hq_context=hq_context)
    return route, ranked


def route_goal(
    goal: str,
    workflows: List[Dict[str, Any]],
    payload: Dict[str, Any],
    digest: Dict[str, Any],
    hq_context: Dict[str, Any],
    components_by_id: Dict[str, Dict[str, Any]],
    history: List[Dict[str, Any]],
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    ranked = rank_workflows(workflows, payload, digest, hq_context, components_by_id, history, goal=goal)
    if ranked[0]["score"] <= 0:
        automatic_route, automatic_ranked = choose_automatic_route(workflows, payload, digest, hq_context, components_by_id, history)
        automatic_route["source"] = "goal-fallback"
        automatic_route["goal"] = goal
        automatic_route["reasons"].insert(0, "No workflow keyword matched directly, so the router fell back to the strongest automatic mission.")
        return automatic_route, automatic_ranked
    return build_route_payload(ranked[0], ranked, components_by_id, source="goal", hq_context=hq_context, goal=goal), ranked


def render_catalog_markdown(generated_at: str, workflows: List[Dict[str, Any]], components_by_id: Dict[str, Dict[str, Any]]) -> str:
    lines = [
        "# OpenClaw SEO Mission Catalog",
        "",
        f"Generated: {generated_at}",
        "",
        "Mission router command:",
        f"- `python3 {HOME / 'squad_memory' / 'refresh_openclaw_seo_missions.py'} --goal \"debug indexing\" --json`",
        "",
    ]
    for workflow in workflows:
        stack_labels = component_labels(workflow["stack"], components_by_id)
        lines.extend(
            [
                f"## {workflow['name']}",
                f"- id: `{workflow['id']}`",
                f"- objective: {workflow['objective']}",
                f"- best when: {workflow['best_when']}",
                f"- cadence: {workflow['cadence']}",
                f"- impact / effort: `{workflow.get('impact', 0)}` / `{workflow.get('effort', 0)}`",
                f"- automation fit: `{workflow.get('automation_fit', 'ambient')}`",
                f"- cooldown: `{workflow.get('cooldown_hours', 0)}`h",
                f"- keywords: {', '.join(workflow['goal_keywords'])}",
                f"- stack: {', '.join(stack_labels)}",
                f"- output: {workflow['output']}",
                "- steps:",
            ]
        )
        lines.extend(f"  {index}. {step}" for index, step in enumerate(workflow["steps"], start=1))
        lines.append("")
    return "\n".join(lines)


def render_mission_prompt(workflow: Dict[str, Any]) -> str:
    return f"""# SEO Mission: {workflow['name']}

Work only inside this SEO workspace.

Read:
- `MEMORY.md`
- `automation/README.md`
- `automation/control/command-center.md`
- `../../memory/imports/codex/graph-hq/phase21/HQ_STATUS.md`
- `../../memory/imports/codex/graph-hq/phase31/GRAPH_STATUS.md`
- `automation/capabilities/local-stack.md`
- `automation/capabilities/workflows.md`
- `automation/missions/catalog.md`
- `automation/missions/execution/{workflow['id']}.md`
- `automation/missions/router/mission-scoreboard.md`
- `automation/digest/latest.md`
- `automation/data/latest-status.md`

Task:
- Execute the `{workflow['name']}` workflow from `automation/capabilities/workflows.md`.
- Follow the ordered task list in `automation/missions/execution/{workflow['id']}.md`.
- Use only the local stack named in that workflow.
- Overwrite `automation/missions/outbox/{workflow['id']}.md`.
- Include sections: `Objective`, `Why Now`, `Execution Queue`, `Stack`, `Next Actions`, and `Files Used`.
- Keep it under 360 words.
- Do not edit any file outside `automation/missions/outbox/{workflow['id']}.md`.
"""


def render_prose_program(workflow: Dict[str, Any]) -> str:
    steps = "; ".join(workflow["steps"])
    return f"""# {workflow['name']}
# OpenClaw SEO mission generated from the local workflow catalog.

agent seo_operator:
  model: sonnet
  prompt: "You are an SEO workflow operator. Work only inside the current OpenClaw SEO workspace."

parallel:
  evidence = session: seo_operator
    prompt: "Read MEMORY.md, automation/control/command-center.md, ../../memory/imports/codex/graph-hq/phase21/HQ_STATUS.md, ../../memory/imports/codex/graph-hq/phase31/GRAPH_STATUS.md, automation/digest/latest.md, automation/data/latest-status.md, and automation/missions/execution/{workflow['id']}.md. Extract the strongest evidence for the {workflow['name']} mission."
  stack = session: seo_operator
    prompt: "Read automation/capabilities/local-stack.md, automation/capabilities/workflows.md, automation/missions/router/mission-scoreboard.md, ../../memory/imports/codex/graph-hq/phase21/HQ_STATUS.md, and automation/missions/execution/{workflow['id']}.md. Identify the local stack and ordered queue for the {workflow['name']} workflow. Steps: {steps}"

session "Write automation/missions/outbox/{workflow['id']}.md with sections Objective, Why Now, Execution Queue, Stack, Next Actions, and Files Used. Use only the {workflow['name']} workflow and do not edit any other file."
  context: {{ evidence, stack }}
"""


def render_mission_fallback(workflow: Dict[str, Any], evaluation: Dict[str, Any], components_by_id: Dict[str, Dict[str, Any]]) -> str:
    lines = [
        f"# {workflow['name']}",
        "",
        f"Generated by deterministic fallback at {now_utc_iso()}.",
        "",
        "## Objective",
        f"- {workflow['objective']}",
        "",
        "## Decision",
        f"- score: `{evaluation['score']}`",
        f"- confidence: `{evaluation['confidence']}`",
        "",
        "## Why Now",
    ]
    lines.extend(f"- {reason}" for reason in evaluation["reasons"][:4])
    lines.extend(["", "## Stack"])
    for label, component_id in zip(component_labels(workflow["stack"], components_by_id), workflow["stack"]):
        lines.append(f"- {label} (`{component_id}`)")
    if evaluation["blockers"]:
        lines.extend(["", "## Blockers"])
        lines.extend(f"- {item}" for item in evaluation["blockers"])
    lines.extend(["", "## Next Actions"])
    lines.extend(f"- {step}" for step in workflow["steps"])
    lines.extend(
        [
            "",
            "## Files Used",
            "- `automation/control/command-center.md`",
            f"- `automation/missions/execution/{workflow['id']}.md`",
            "- `automation/missions/router/mission-scoreboard.md`",
            "- `automation/digest/latest.md`",
            "- `automation/data/latest-status.md`",
            "- `automation/capabilities/local-stack.md`",
            "- `automation/capabilities/workflows.md`",
            "",
        ]
    )
    return "\n".join(lines)


def render_route_markdown(route: Dict[str, Any], title: str) -> str:
    selected = route["selected"]
    lines = [
        f"# {title}",
        "",
        f"Generated by deterministic fallback at {route['generated_at']}.",
    ]
    if route.get("goal"):
        lines.extend(["", "## Goal", f"- {route['goal']}"])
    lines.extend(
        [
            "",
            "## Decision",
            f"- selected: {selected['name']} (`{selected['id']}`)",
            f"- score: `{route['score']}`",
            f"- confidence: `{route['confidence']}`",
            f"- cadence: `{selected['cadence']}`",
            "",
            "## Why This Wins Now",
        ]
    )
    lines.extend(f"- {reason}" for reason in route["reasons"])
    lines.extend(["", "## Score Breakdown"])
    for key, value in route["score_breakdown"].items():
        lines.append(f"- {key.replace('_', ' ')}: `{value}`")
    if route.get("hq", {}).get("available"):
        lines.extend(
            [
                "",
                "## HQ Signals",
                f"- SEO queue hold: `{route['hq']['seo_queue_hold']}`",
                f"- SEO stale sources: `{route['hq']['seo_stale_sources']}`",
                f"- graph topics: `{route['hq']['graph_topics_total']}`",
                f"- graph memory paths: `{route['hq']['graph_memory_paths_total']}`",
            ]
        )
    lines.extend(["", "## Stack"])
    lines.extend(f"- {label}" for label in selected["stack_labels"])
    if route["blockers"]:
        lines.extend(["", "## Blockers"])
        lines.extend(f"- {item}" for item in route["blockers"])
    lines.extend(["", "## First Actions"])
    lines.append(f"- Open `{selected['current_queue_path']}` to see the active ordered task list.")
    lines.append(f"- Open `{selected['queue_path']}` or `{selected['prompt_path']}` for the workflow-specific operating plan.")
    lines.append(f"- Write or review `{selected['outbox_path']}`.")
    lines.append("- Compare the output against the command center and the mission scoreboard before taking action.")
    lines.extend(["", "## Switch Conditions"])
    lines.extend(f"- {item}" for item in route["switch_conditions"])
    if route["alternatives"]:
        lines.extend(["", "## Alternatives"])
        for item in route["alternatives"]:
            lines.append(
                f"- {item['name']} (`{item['id']}`) score={item['score']} confidence={item['confidence']} gap={item['score_gap']} | {item['why']}"
            )
    lines.append("")
    return "\n".join(lines)


def render_scoreboard_markdown(ranked_evals: List[Dict[str, Any]]) -> str:
    lines = [
        "# SEO Mission Scoreboard",
        "",
        f"Generated: {now_utc_iso()}",
        "",
    ]
    for index, evaluation in enumerate(ranked_evals, start=1):
        workflow = evaluation["workflow"]
        lines.extend(
            [
                f"## {index}. {workflow['name']}",
                f"- id: `{workflow['id']}`",
                f"- score / confidence: `{evaluation['score']}` / `{evaluation['confidence']}`",
                f"- impact / effort: `{workflow.get('impact', 0)}` / `{workflow.get('effort', 0)}`",
                f"- automation fit: `{workflow.get('automation_fit', 'ambient')}`",
                "- breakdown:",
            ]
        )
        lines.extend(
            f"  - {key.replace('_', ' ')} = {value}"
            for key, value in evaluation["score_breakdown"].items()
        )
        lines.append("- why:")
        lines.extend(f"  - {reason}" for reason in evaluation["reasons"][:3])
        if evaluation["blockers"]:
            lines.append("- blockers:")
            lines.extend(f"  - {item}" for item in evaluation["blockers"])
        lines.append("")
    return "\n".join(lines)


def task_component_state(task: Dict[str, Any], components_by_id: Dict[str, Dict[str, Any]]) -> Tuple[List[str], List[str]]:
    partial: List[str] = []
    missing: List[str] = []
    for component_id in task.get("stack", []):
        component = components_by_id.get(component_id, {})
        label = component.get("label", component_id)
        status = component.get("status", "missing")
        if status == "missing":
            missing.append(label)
        elif status == "partial":
            partial.append(label)
    return partial, missing


def build_execution_queue_payload(
    workflow: Dict[str, Any],
    evaluation: Dict[str, Any],
    components_by_id: Dict[str, Dict[str, Any]],
    route_source: str,
    goal: str | None = None,
) -> Dict[str, Any]:
    templates = workflow.get("queue_template", [])
    template_titles = {task["id"]: task["title"] for task in templates}
    items: List[Dict[str, Any]] = []

    for index, task in enumerate(templates, start=1):
        partial, missing = task_component_state(task, components_by_id)
        dependency_titles = [template_titles.get(dep, dep) for dep in task.get("depends_on", [])]

        blockers: List[str] = []
        if missing:
            blockers.extend(f"{label} is missing." for label in missing)
        elif dependency_titles:
            blockers.extend(f"Wait for {title}." for title in dependency_titles)
        elif partial:
            blockers.extend(f"{label} is only partially ready." for label in partial)

        if missing:
            status = "blocked"
        elif dependency_titles:
            status = "queued"
        elif partial:
            status = "at-risk"
        elif task.get("priority") == "now":
            status = "ready"
        else:
            status = "queued"

        task_id = f"{workflow['id']}.{task['id']}"
        artifact_root = f"automation/missions/execution/artifacts/{workflow['id']}"
        items.append(
            {
                "id": task_id,
                "order": index,
                "title": task["title"],
                "objective": task["objective"],
                "status": status,
                "priority": task["priority"],
                "owner": task["owner"],
                "stack": task.get("stack", []),
                "stack_labels": component_labels(task.get("stack", []), components_by_id),
                "deliverable": task["deliverable"],
                "depends_on": [f"{workflow['id']}.{dep}" for dep in task.get("depends_on", [])],
                "blocked_by": blockers,
                "artifact_markdown_path": f"{artifact_root}/{task['id']}.md",
                "artifact_json_path": f"{artifact_root}/{task['id']}.json",
            }
        )

    current_focus = next((item for item in items if item["status"] in {"ready", "at-risk"}), None)
    if not current_focus and items:
        current_focus = next((item for item in items if item["status"] == "blocked"), items[0])

    summary = {
        "total": len(items),
        "ready": sum(1 for item in items if item["status"] == "ready"),
        "at_risk": sum(1 for item in items if item["status"] == "at-risk"),
        "queued": sum(1 for item in items if item["status"] == "queued"),
        "blocked": sum(1 for item in items if item["status"] == "blocked"),
    }

    return {
        "generated_at": now_utc_iso(),
        "route_source": route_source,
        "goal": goal,
        "mission": {
            "id": workflow["id"],
            "name": workflow["name"],
            "score": evaluation["score"],
            "confidence": evaluation["confidence"],
            "objective": workflow["objective"],
            "output": workflow["output"],
            "outbox_path": f"automation/missions/outbox/{workflow['id']}.md",
        },
        "summary": summary,
        "why_now": evaluation["reasons"][:4],
        "current_focus": current_focus,
        "items": items,
        "context_files": [
            "automation/control/command-center.md",
            "automation/missions/router/mission-scoreboard.md",
            "../../memory/imports/codex/graph-hq/phase21/HQ_STATUS.md",
            "../../memory/imports/codex/graph-hq/phase31/GRAPH_STATUS.md",
            "automation/digest/latest.md",
            "automation/data/latest-status.md",
            f"automation/missions/prompts/{workflow['id']}.md",
        ],
    }


def build_progress_signals(
    workspace: Path,
    workflow: Dict[str, Any],
    queue_payload: Dict[str, Any],
) -> Dict[str, Any]:
    task_artifacts = {
        item["id"]: artifact_snapshot(workspace / item["artifact_markdown_path"])
        for item in queue_payload.get("items", [])
    }
    return {
        "hq_plan": artifact_snapshot(workspace / "automation" / "hq" / "current-plan.md"),
        "mission_outbox": artifact_snapshot(workspace / "automation" / "missions" / "outbox" / f"{workflow['id']}.md"),
        "task_artifacts": task_artifacts,
    }


def load_progress_state(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {"missions": {}}
    payload = load_json(path)
    if not isinstance(payload, dict):
        return {"missions": {}}
    if not isinstance(payload.get("missions"), dict):
        payload["missions"] = {}
    return payload


def save_progress_state(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def dependency_ready(item: Dict[str, Any], completed_ids: set[str]) -> bool:
    return all(dep in completed_ids for dep in item.get("depends_on", []))


def base_queue_status(item: Dict[str, Any]) -> str:
    if item["blocked_by"]:
        has_missing = any("missing" in blocker.lower() for blocker in item["blocked_by"])
        if has_missing:
            return "blocked"
        return "queued"
    return "at-risk" if item.get("status") == "at-risk" else "ready"


def apply_auto_progress(
    workspace: Path,
    workflow: Dict[str, Any],
    queue_payload: Dict[str, Any],
    progress_state_path: Path,
) -> Dict[str, Any]:
    state = load_progress_state(progress_state_path)
    mission_id = workflow["id"]
    mission_state = state["missions"].get(mission_id, {})
    completed_ids = {
        item_id
        for item_id in mission_state.get("completed_task_ids", [])
        if isinstance(item_id, str)
    }
    current_task_ids = {item["id"] for item in queue_payload["items"]}
    completed_ids &= current_task_ids

    signals = build_progress_signals(workspace, workflow, queue_payload)
    signal_history = mission_state.get("signals", {}) if isinstance(mission_state.get("signals"), dict) else {}
    artifact_history = mission_state.get("artifacts", {}) if isinstance(mission_state.get("artifacts"), dict) else {}
    advanced: List[Dict[str, Any]] = []

    for item in queue_payload["items"]:
        snapshot = signals["task_artifacts"].get(item["id"], {})
        if not snapshot.get("exists") or not snapshot.get("updated_at"):
            continue
        if not dependency_ready(item, completed_ids):
            continue
        snapshot_updated_at = snapshot["updated_at"]
        if item["id"] in completed_ids and artifact_history.get(item["id"]) == snapshot_updated_at:
            continue
        completed_ids.add(item["id"])
        artifact_history[item["id"]] = snapshot_updated_at
        advanced.append(
            {
                "signal": "task_artifact",
                "task_id": item["id"],
                "task_title": item["title"],
                "updated_at": snapshot_updated_at,
            }
        )

    pending_items = [item for item in queue_payload["items"] if item["id"] not in completed_ids]
    for signal_name in ("hq_plan", "mission_outbox"):
        snapshot = signals[signal_name]
        if snapshot["mode"] != "live" or not snapshot.get("updated_at"):
            continue
        if signal_history.get(signal_name) == snapshot["updated_at"]:
            continue
        next_item = next((item for item in pending_items if dependency_ready(item, completed_ids)), None)
        if not next_item:
            signal_history[signal_name] = snapshot["updated_at"]
            continue
        completed_ids.add(next_item["id"])
        signal_history[signal_name] = snapshot["updated_at"]
        advanced.append(
            {
                "signal": signal_name,
                "task_id": next_item["id"],
                "task_title": next_item["title"],
                "updated_at": snapshot["updated_at"],
            }
        )
        pending_items = [item for item in queue_payload["items"] if item["id"] not in completed_ids]

    progressed_items: List[Dict[str, Any]] = []
    for item in queue_payload["items"]:
        next_item = dict(item)
        if next_item["id"] in completed_ids:
            next_item["status"] = "done"
            next_item["blocked_by"] = []
        else:
            status = base_queue_status(next_item)
            if status == "queued" and dependency_ready(next_item, completed_ids):
                status = "ready"
            next_item["status"] = status
        progressed_items.append(next_item)

    current_focus = next(
        (item for item in progressed_items if item["status"] in {"ready", "at-risk"}),
        next((item for item in progressed_items if item["status"] == "blocked"), None),
    )

    summary = {
        "total": len(progressed_items),
        "done": sum(1 for item in progressed_items if item["status"] == "done"),
        "ready": sum(1 for item in progressed_items if item["status"] == "ready"),
        "at_risk": sum(1 for item in progressed_items if item["status"] == "at-risk"),
        "queued": sum(1 for item in progressed_items if item["status"] == "queued"),
        "blocked": sum(1 for item in progressed_items if item["status"] == "blocked"),
    }

    mission_state = {
        "completed_task_ids": [item["id"] for item in progressed_items if item["status"] == "done"],
        "signals": signal_history,
        "artifacts": artifact_history,
        "updated_at": now_utc_iso(),
        "current_focus_id": current_focus["id"] if current_focus else None,
    }
    state["missions"][mission_id] = mission_state
    save_progress_state(progress_state_path, state)

    queue_payload["items"] = progressed_items
    queue_payload["summary"] = summary
    queue_payload["current_focus"] = current_focus
    queue_payload["auto_progress"] = {
        "state_path": str(progress_state_path),
        "completed_task_ids": mission_state["completed_task_ids"],
        "signals": signals,
        "artifacts": artifact_history,
        "advanced": advanced,
    }
    return queue_payload


def render_execution_queue_markdown(queue: Dict[str, Any]) -> str:
    mission = queue["mission"]
    lines = [
        f"# Execution Queue: {mission['name']}",
        "",
        f"Generated: {queue['generated_at']}",
        "",
        "## Mission",
        f"- id: `{mission['id']}`",
        f"- score / confidence: `{mission['score']}` / `{mission['confidence']}`",
        f"- output: `{mission['outbox_path']}`",
        "",
        "## Queue Summary",
        f"- total: `{queue['summary']['total']}`",
        f"- done: `{queue['summary'].get('done', 0)}`",
        f"- ready: `{queue['summary'].get('ready', 0)}`",
        f"- at-risk: `{queue['summary'].get('at_risk', 0)}`",
        f"- queued: `{queue['summary'].get('queued', 0)}`",
        f"- blocked: `{queue['summary'].get('blocked', 0)}`",
        "",
        "## Why Now",
    ]
    lines.extend(f"- {reason}" for reason in queue["why_now"])

    if queue.get("current_focus"):
        focus = queue["current_focus"]
        lines.extend(
            [
                "",
                "## Current Focus",
                f"- task: {focus['title']} (`{focus['id']}`)",
                f"- status / priority / owner: `{focus['status']}` / `{focus['priority']}` / `{focus['owner']}`",
                f"- deliverable: {focus['deliverable']}",
            ]
        )
        if focus["blocked_by"]:
            lines.append(f"- blockers: {'; '.join(focus['blocked_by'])}")

    auto_progress = queue.get("auto_progress")
    if auto_progress:
        lines.extend(["", "## Auto Progress"])
        lines.append(f"- state: `{auto_progress['state_path']}`")
        if auto_progress["advanced"]:
            for event in auto_progress["advanced"]:
                lines.append(
                    f"- advanced: `{event['task_title']}` via `{event['signal']}` at `{event['updated_at']}`"
                )
        else:
            lines.append("- advanced: none in this refresh.")

    lines.extend(["", "## Tasks"])
    for item in queue["items"]:
        lines.extend(
            [
                f"### {item['order']}. {item['title']}",
                f"- id: `{item['id']}`",
                f"- status / priority / owner: `{item['status']}` / `{item['priority']}` / `{item['owner']}`",
                f"- objective: {item['objective']}",
                f"- stack: {', '.join(item['stack_labels'])}",
                f"- deliverable: {item['deliverable']}",
                f"- artifact: `{item['artifact_markdown_path']}`",
                f"- depends on: {', '.join(item['depends_on']) if item['depends_on'] else 'none'}",
            ]
        )
        if item["blocked_by"]:
            lines.append(f"- blockers: {'; '.join(item['blocked_by'])}")
        lines.append("")

    lines.extend(["## Context Files"])
    lines.extend(f"- `{path}`" for path in queue["context_files"])
    lines.append("")
    return "\n".join(lines)


def write_managed_text(path: Path, text: str) -> None:
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if "Generated by deterministic fallback" not in current and "Awaiting the first OpenClaw mission run." not in current:
            return
    path.write_text(text, encoding="utf-8")


def record_history(history_path: Path, route: Dict[str, Any]) -> List[Dict[str, Any]]:
    entries = load_route_history(history_path.parent)
    current = {
        "generated_at": route["generated_at"],
        "selected_id": route["selected"]["id"],
        "selected_name": route["selected"]["name"],
        "score": route["score"],
        "confidence": route["confidence"],
        "source": route["source"],
    }
    if not entries or entries[-1] != current:
        entries.append(current)
    save_route_history(history_path, entries)
    return entries


def refresh_openclaw_seo_missions(
    workspace: Path,
    payload: Dict[str, Any],
    digest: Dict[str, Any],
    goal: str | None = None,
    graph_hq_root: Path | None = None,
) -> Dict[str, Any]:
    components, workflows = load_capabilities(workspace)
    components_by_id = {component["id"]: component for component in components}
    hq_context = build_graph_hq_context(workspace, graph_hq_root=graph_hq_root)

    missions_root = workspace / "automation" / "missions"
    prompts_dir = missions_root / "prompts"
    outbox_dir = missions_root / "outbox"
    prose_dir = missions_root / "prose"
    execution_dir = missions_root / "execution"
    router_dir = missions_root / "router"
    for path in (missions_root, prompts_dir, outbox_dir, prose_dir, execution_dir, router_dir):
        path.mkdir(parents=True, exist_ok=True)

    generated_at = now_utc_iso()
    catalog_json = missions_root / "catalog.json"
    catalog_md = missions_root / "catalog.md"
    readme_path = missions_root / "README.md"
    history_path = router_dir / "history.json"

    catalog_payload = {
        "generated_at": generated_at,
        "workflows": workflows,
    }
    catalog_json.write_text(json.dumps(catalog_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    catalog_md.write_text(render_catalog_markdown(generated_at, workflows, components_by_id), encoding="utf-8")
    readme_path.write_text(mission_readme(), encoding="utf-8")

    history = load_route_history(router_dir)
    automatic_route, ranked_evals = choose_automatic_route(workflows, payload, digest, hq_context, components_by_id, history)
    automatic_history = record_history(history_path, automatic_route)
    automatic_route["history_tail"] = automatic_history[-6:]
    automatic_evaluations = {evaluation["workflow"]["id"]: evaluation for evaluation in ranked_evals}

    for evaluation in ranked_evals:
        workflow = evaluation["workflow"]
        prompt_path = prompts_dir / f"{workflow['id']}.md"
        prose_path = prose_dir / f"{workflow['id']}.prose"
        outbox_path = outbox_dir / f"{workflow['id']}.md"
        queue_json_path = execution_dir / f"{workflow['id']}.json"
        queue_md_path = execution_dir / f"{workflow['id']}.md"
        prompt_path.write_text(render_mission_prompt(workflow), encoding="utf-8")
        prose_path.write_text(render_prose_program(workflow), encoding="utf-8")
        write_managed_text(outbox_path, render_mission_fallback(workflow, evaluation, components_by_id))
        queue_payload = build_execution_queue_payload(
            workflow=workflow,
            evaluation=evaluation,
            components_by_id=components_by_id,
            route_source="automatic",
        )
        queue_json_path.write_text(json.dumps(queue_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        queue_md_path.write_text(render_execution_queue_markdown(queue_payload), encoding="utf-8")

    next_best_json = router_dir / "next-best-mission.json"
    next_best_md = router_dir / "next-best-mission.md"
    next_best_deterministic_md = router_dir / "next-best-mission-deterministic.md"
    current_mission_path = router_dir / "current-mission.md"
    scoreboard_json = router_dir / "mission-scoreboard.json"
    scoreboard_md = router_dir / "mission-scoreboard.md"

    scoreboard_payload = {
        "generated_at": automatic_route["generated_at"],
        "selected_id": automatic_route["selected"]["id"],
        "rankings": [
            {
                "id": evaluation["workflow"]["id"],
                "name": evaluation["workflow"]["name"],
                "score": evaluation["score"],
                "confidence": evaluation["confidence"],
                "blockers": evaluation["blockers"],
                "score_breakdown": evaluation["score_breakdown"],
                "reasons": evaluation["reasons"][:3],
            }
            for evaluation in ranked_evals
        ],
    }

    next_best_json.write_text(json.dumps(automatic_route, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    next_best_deterministic_md.write_text(
        render_route_markdown(automatic_route, "Next Best SEO Mission (Deterministic)"),
        encoding="utf-8",
    )
    write_managed_text(next_best_md, render_route_markdown(automatic_route, "Next Best SEO Mission"))
    scoreboard_json.write_text(json.dumps(scoreboard_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    scoreboard_md.write_text(render_scoreboard_markdown(ranked_evals), encoding="utf-8")
    active_route = automatic_route
    active_evaluations = automatic_evaluations

    goal_route_payload = None
    if goal:
        goal_route_payload, goal_ranked = route_goal(goal, workflows, payload, digest, hq_context, components_by_id, history)
        goal_evaluations = {evaluation["workflow"]["id"]: evaluation for evaluation in goal_ranked}
        goal_json = router_dir / "goal-route.json"
        goal_md = router_dir / "goal-route.md"
        goal_queue_json = execution_dir / "goal-queue.json"
        goal_queue_md = execution_dir / "goal-queue.md"
        goal_json.write_text(json.dumps(goal_route_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        goal_md.write_text(render_route_markdown(goal_route_payload, "SEO Goal Route"), encoding="utf-8")
        goal_queue_payload = build_execution_queue_payload(
            workflow=goal_evaluations[goal_route_payload["selected"]["id"]]["workflow"],
            evaluation=goal_evaluations[goal_route_payload["selected"]["id"]],
            components_by_id=components_by_id,
            route_source=goal_route_payload["source"],
            goal=goal,
        )
        goal_queue_json.write_text(json.dumps(goal_queue_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        goal_queue_md.write_text(render_execution_queue_markdown(goal_queue_payload), encoding="utf-8")
        scoreboard_payload["goal_rankings"] = [
            {
                "id": evaluation["workflow"]["id"],
                "name": evaluation["workflow"]["name"],
                "score": evaluation["score"],
                "confidence": evaluation["confidence"],
                "reasons": evaluation["reasons"][:2],
            }
            for evaluation in goal_ranked
        ]
        scoreboard_json.write_text(json.dumps(scoreboard_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        active_route = goal_route_payload
        active_evaluations = goal_evaluations

    current_queue_json = execution_dir / "current-queue.json"
    current_queue_md = execution_dir / "current-queue.md"
    progress_state_path = execution_dir / "progress-state.json"
    current_queue_payload = build_execution_queue_payload(
        workflow=active_evaluations[active_route["selected"]["id"]]["workflow"],
        evaluation=active_evaluations[active_route["selected"]["id"]],
        components_by_id=components_by_id,
        route_source=active_route["source"],
        goal=active_route.get("goal"),
    )
    current_queue_payload = apply_auto_progress(
        workspace=workspace,
        workflow=active_evaluations[active_route["selected"]["id"]]["workflow"],
        queue_payload=current_queue_payload,
        progress_state_path=progress_state_path,
    )
    current_queue_json.write_text(json.dumps(current_queue_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    current_queue_md.write_text(render_execution_queue_markdown(current_queue_payload), encoding="utf-8")
    active_workflow_queue_json = execution_dir / f"{active_route['selected']['id']}.json"
    active_workflow_queue_md = execution_dir / f"{active_route['selected']['id']}.md"
    active_workflow_queue_json.write_text(json.dumps(current_queue_payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    active_workflow_queue_md.write_text(render_execution_queue_markdown(current_queue_payload), encoding="utf-8")
    current_mission_path.write_text(
        (prompts_dir / f"{active_route['selected']['id']}.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    return {
        "status": "ok",
        "generated_at": generated_at,
        "workspace": str(workspace),
        "mission_count": len(workflows),
        "hq_context": hq_context,
        "catalog_json": str(catalog_json),
        "catalog_markdown": str(catalog_md),
        "automatic_route": automatic_route,
        "goal_route": goal_route_payload,
        "history_path": str(history_path),
        "scoreboard_json": str(scoreboard_json),
        "scoreboard_markdown": str(scoreboard_md),
        "current_queue": current_queue_payload,
        "progress_state_path": str(progress_state_path),
        "current_queue_json": str(current_queue_json),
        "current_queue_markdown": str(current_queue_md),
    }


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace)
    payload = load_json(Path(args.status_json))
    digest = load_json(Path(args.digest_json))
    result = refresh_openclaw_seo_missions(
        workspace=workspace,
        payload=payload,
        digest=digest,
        goal=args.goal,
        graph_hq_root=Path(args.graph_hq_root) if args.graph_hq_root else None,
    )
    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=True))
    else:
        route = result["goal_route"] or result["automatic_route"]
        print(
            f"OpenClaw SEO missions refreshed | missions={result['mission_count']} "
            f"selected={route['selected']['id']} workspace={result['workspace']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
